namespace: app

replicas: 1
app_name: api
init_name: alembic

nginx-ingress:
  controller:
    enableCustomResources: true
    service:
      httpPort:
        port: 80
        nodePort: 30080
        targetPort: 80

service:
  type: ClusterIP
  port: 80

images:
  app:
    repo: nginx
    tag: latest
    pullPolicy: Always
  init:
    repo: busybox
    tag: 1.28
    pullPolicy: Always

config:
  app:
    SOME_VAR: some_val
  init:
    ANOTHER_VAR: another_val
