namespace: app

replicas: 1
app_name: api
init_name: alembic

service:
  type: ClusterIP
  port: 80

images:
  app:
    repo: nginx         # specify api image here
    tag: latest         # delete this to use .Chart.AppVersion as tag
    pullPolicy: Always
  init:
    repo: busybox       # specify alembic image here
    tag: 1.28           # delete this to use .Chart.AppVersion as tag
    pullPolicy: Always

config:
  app:
    SOME_VAR: some_val
  init:
    ANOTHER_VAR: another_val
