apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentdconf
  namespace: {{ .Values.namespace }}
data:
  fluent.conf: |
      <source>
        @type tail
        path {{ .Values.logs.path }}/*.log
        pos_file /tmp/{{ .Values.app_name }}-app.log.pos
        tag {{ .Values.app_name }}-app.file.logs
        <parse>
          @type json
          time_key time
          time_type string
          time_format "%Y-%m-%dT%H:%M:%S.%NZ"
          #keep_time_key false
        </parse>
      </source>

      <filter {{ .Values.app_name }}-app.file.logs>
        @type record_transformer
        <record>
        hostname ${hostname}
        </record>
      </filter>

      <match {{ .Values.app_name }}-app.file.logs>
        @type forward
        send_timeout 60s
        recover_wait 10s
        hard_timeout 60s
        <server>
          name fluentd_daemonset
          host {{ .Values.logs.forward.host }}
          port {{ .Values.logs.forward.port }}
          weight 60
        </server>
        <secondary>
          @type stdout
        </secondary>
      </match>
