apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.init_name }}-conf
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.config.init }}
  {{ $key }}: {{ $val }}
  {{- end}}
