apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      nodePort: 30080
  selector:
    app: {{ .Values.app_name }}
